import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Brain, MessageSquare, Send, Loader2, Users, Copy, Check } from "lucide-react";
import { renderAvatar } from "../pages/ProfilePage";

const TABS = [
  { id: "chat", label: "Chat", icon: MessageSquare },
  { id: "ai", label: "Ask AI", icon: Brain },
];

// ── Custom Code Block with Copy Button ───────────────────
const CodeBlock = ({ language, code }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy code: ", err);
    }
  };

  return (
    <div className="ai-code-container">
      <div className="ai-code-header">
        <span className="ai-code-lang">{language || "code"}</span>
        <button onClick={handleCopy} className="ai-code-copy-btn">
          {copied ? (
            <>
              <Check size={11} style={{ marginRight: 4 }} />
              Copied!
            </>
          ) : (
            <>
              <Copy size={11} style={{ marginRight: 4 }} />
              Copy code
            </>
          )}
        </button>
      </div>
      <pre className="ai-code-pre">
        <code>{code}</code>
      </pre>
    </div>
  );
};

// ── Simple Markdown to JSX Renderer ──────────────────────
const renderMarkdown = (text) => {
  if (!text) return null;

  // Clean up escaped dollar signs (e.g. \$) generated by AI to avoid LaTeX formatting
  const cleanedText = text.replace(/\\\$/g, "$");

  // Split by code blocks first
  const parts = cleanedText.split(/(```[\s\S]*?```)/g);

  const elements = [];
  let key = 0;

  parts.forEach((part) => {
    if (part.startsWith("```") && part.endsWith("```")) {
      // Code block
      const lines = part.slice(3, -3);
      const firstNewline = lines.indexOf("\n");
      const language = firstNewline >= 0 ? lines.slice(0, firstNewline).trim() : "";
      const code = firstNewline >= 0 ? lines.slice(firstNewline + 1) : lines;
      elements.push(
        <CodeBlock key={key++} language={language} code={code} />
      );
    } else {
      // Process non-code-block text
      const lines = part.split("\n");
      let i = 0;

      while (i < lines.length) {
        const line = lines[i];

        // Empty line
        if (line.trim() === "") {
          i++;
          continue;
        }

        // Headings
        const headingMatch = line.match(/^(#{1,3})\s+(.+)/);
        if (headingMatch) {
          const level = headingMatch[1].length;
          const content = headingMatch[2];
          const Tag = `h${level}`;
          elements.push(<Tag key={key++}>{renderInline(content)}</Tag>);
          i++;
          continue;
        }

        // Horizontal rule
        if (line.trim().match(/^(-{3,}|\*{3,}|_{3,})$/)) {
          elements.push(<hr key={key++} />);
          i++;
          continue;
        }

        // Unordered list items
        if (line.trim().match(/^[-*]\s+/)) {
          const listItems = [];
          while (i < lines.length && lines[i].trim().match(/^[-*]\s+/)) {
            const itemText = lines[i].trim().replace(/^[-*]\s+/, "");
            listItems.push(<li key={key++}>{renderInline(itemText)}</li>);
            i++;
          }
          elements.push(<ul key={key++}>{listItems}</ul>);
          continue;
        }

        // Ordered list items
        if (line.trim().match(/^\d+\.\s+/)) {
          const listItems = [];
          while (i < lines.length && lines[i].trim().match(/^\d+\.\s+/)) {
            const itemText = lines[i].trim().replace(/^\d+\.\s+/, "");
            listItems.push(<li key={key++}>{renderInline(itemText)}</li>);
            i++;
          }
          elements.push(<ol key={key++}>{listItems}</ol>);
          continue;
        }

        // Blockquote
        if (line.trim().startsWith(">")) {
          const quoteLines = [];
          while (i < lines.length && lines[i].trim().startsWith(">")) {
            quoteLines.push(lines[i].trim().replace(/^>\s?/, ""));
            i++;
          }
          elements.push(
            <blockquote key={key++}>
              <p>{renderInline(quoteLines.join(" "))}</p>
            </blockquote>
          );
          continue;
        }

        // Regular paragraph
        elements.push(<p key={key++}>{renderInline(line)}</p>);
        i++;
      }
    }
  });

  return elements;
};

// Render inline formatting (bold, inline code)
const renderInline = (text) => {
  if (!text) return text;
  const parts = [];
  let remaining = text;
  let key = 0;

  while (remaining.length > 0) {
    // Inline code
    const codeMatch = remaining.match(/`([^`]+)`/);
    // Bold
    const boldMatch = remaining.match(/\*\*([^*]+)\*\*/);

    let firstMatch = null;
    let matchType = null;

    if (codeMatch && (!boldMatch || codeMatch.index <= boldMatch.index)) {
      firstMatch = codeMatch;
      matchType = "code";
    } else if (boldMatch) {
      firstMatch = boldMatch;
      matchType = "bold";
    }

    if (!firstMatch) {
      parts.push(remaining);
      break;
    }

    // Add text before the match
    if (firstMatch.index > 0) {
      parts.push(remaining.slice(0, firstMatch.index));
    }

    if (matchType === "code") {
      parts.push(<code key={key++}>{firstMatch[1]}</code>);
    } else if (matchType === "bold") {
      parts.push(<strong key={key++}>{firstMatch[1]}</strong>);
    }

    remaining = remaining.slice(firstMatch.index + firstMatch[0].length);
  }

  return parts;
};

// ── Room Chat Message ────────────────────────────────────
const RoomChatMessage = ({ msg, currentUser, senderAvatar, senderColor }) => {
  const isMe = msg.username === currentUser;
  return (
    <motion.div
      style={{
        display: "flex",
        gap: 8,
        alignItems: "flex-start",
        flexDirection: isMe ? "row-reverse" : "row",
        maxWidth: "100%",
        margin: "4px 0",
      }}
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.2 }}
    >
      <div style={{ flexShrink: 0 }}>
        {senderAvatar ? (
          renderAvatar(senderAvatar, msg.username, 26)
        ) : (
          <div
            style={{
              width: 26,
              height: 26,
              borderRadius: "50%",
              background: senderColor || "var(--accent-cyan)",
              color: "#fff",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontSize: "11px",
              fontWeight: 700,
            }}
          >
            {msg.username?.[0]?.toUpperCase()}
          </div>
        )}
      </div>

      <div
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: isMe ? "flex-end" : "flex-start",
          maxWidth: "calc(100% - 34px)",
        }}
      >
        {!isMe && (
          <span
            style={{
              fontSize: "10px",
              color: senderColor || "var(--accent-cyan)",
              fontFamily: "var(--font-mono)",
              marginBottom: 2,
              paddingLeft: 4,
            }}
          >
            {msg.username}
          </span>
        )}
        <div
          style={{
            ...styles.bubble,
            background: isMe ? "rgba(255, 255, 255, 0.08)" : "rgba(255, 255, 255, 0.03)",
            border: `1px solid ${isMe ? "rgba(255, 255, 255, 0.2)" : "var(--border)"}`,
            borderRadius: isMe ? "12px 12px 4px 12px" : "12px 12px 12px 4px",
          }}
        >
          <p style={styles.msgText}>{msg.message}</p>
        </div>
        <span
          style={{
            fontSize: "9px",
            color: "var(--text-muted)",
            marginTop: 2,
            paddingLeft: isMe ? 0 : 4,
            paddingRight: isMe ? 4 : 0,
          }}
        >
          {(() => {
            const date = new Date(msg.timestamp);
            const dateStr = date.toLocaleDateString([], { month: "short", day: "numeric" });
            const timeStr = date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
            return `${dateStr}, ${timeStr}`;
          })()}
        </span>
      </div>
    </motion.div>
  );
};

// ── AI Chat Message ──────────────────────────────────────
const AIChatMessage = ({ msg }) => (
  <motion.div
    style={{
      ...styles.msgWrap,
      alignItems: msg.role === "user" ? "flex-end" : "flex-start",
    }}
    initial={{ opacity: 0, y: 6 }}
    animate={{ opacity: 1, y: 0 }}
    transition={{ duration: 0.2 }}
  >
    {msg.role === "assistant" && (
      <span style={styles.aiLabel}>
        <Brain size={10} color="var(--accent-cyan)" /> AI
      </span>
    )}
    <div
      style={{
        ...styles.bubble,
        background: msg.role === "user" ? "rgba(255,255,255,0.12)" : "var(--bg-elevated)",
        border: `1px solid ${msg.role === "user" ? "rgba(255,255,255,0.25)" : "var(--border)"}`,
        borderRadius: msg.role === "user" ? "12px 12px 4px 12px" : "12px 12px 12px 4px",
      }}
    >
      {msg.role === "assistant" ? (
        <div className="ai-md-content">{renderMarkdown(msg.content)}</div>
      ) : (
        <p style={{ ...styles.msgText, whiteSpace: "pre-wrap" }}>{msg.content}</p>
      )}
    </div>
  </motion.div>
);

// ── Main Panel ───────────────────────────────────────────
const AIPanel = ({
  currentUser,
  users,
  messages,
  onSendRoomMessage,
  chatHistory,
  chatLoading,
  onSendChat,
  code,
  language,
  lastEditedBy,
}) => {
  const [activeTab, setActiveTab] = useState("chat");
  const [roomInput, setRoomInput] = useState("");
  const [aiInput, setAiInput] = useState("");
  const [showMembers, setShowMembers] = useState(false);

  const chatBottomRef = useRef(null);
  const aiBottomRef = useRef(null);
  const roomTextareaRef = useRef(null);
  const aiTextareaRef = useRef(null);

  useEffect(() => {
    chatBottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  useEffect(() => {
    aiBottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [chatHistory, chatLoading]);

  // Auto-expand textarea for room chat
  useEffect(() => {
    const adjustHeight = () => {
      const textarea = roomTextareaRef.current;
      if (textarea) {
        textarea.style.height = "34px";
        if (roomInput) {
          textarea.style.height = `${Math.min(textarea.scrollHeight, 120)}px`;
        }
      }
    };

    adjustHeight();
    const timer = setTimeout(adjustHeight, 100);
    return () => clearTimeout(timer);
  }, [roomInput, activeTab]);

  // Auto-expand textarea for AI chat
  useEffect(() => {
    const adjustHeight = () => {
      const textarea = aiTextareaRef.current;
      if (textarea) {
        textarea.style.height = "34px";
        if (aiInput) {
          textarea.style.height = `${Math.min(textarea.scrollHeight, 120)}px`;
        }
      }
    };

    adjustHeight();
    const timer = setTimeout(adjustHeight, 100);
    return () => clearTimeout(timer);
  }, [aiInput, activeTab]);

  const handleRoomSend = () => {
    if (!roomInput.trim()) return;
    onSendRoomMessage(roomInput);
    setRoomInput("");
  };

  const handleAiSend = () => {
    if (!aiInput.trim()) return;
    onSendChat(aiInput, code, language);
    setAiInput("");
  };

  return (
    <div style={styles.panel}>
      {/* ── Tabs Segmented Control ─────────────────── */}
      <div
        style={{
          padding: "12px 16px 6px",
          background: "rgba(20,20,26,0.2)",
          borderBottom: "1px solid var(--border)",
        }}
      >
        <div className="tabs-segment-container">
          <div
            className="tabs-segment-slider"
            style={{
              width: "calc(50% - 4px)",
              left: activeTab === "chat" ? "4px" : "calc(50%)",
            }}
          />
          {TABS.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`tabs-segment-btn ${activeTab === tab.id ? "active" : ""}`}
            >
              <tab.icon size={13} />
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      {/* ── ROOM CHAT TAB ────────────────────────── */}
      {activeTab === "chat" && (
        <div style={styles.tabWrap}>
          {/* Online members toggle */}
          <div style={styles.membersHeader}>
            <button style={styles.membersToggle} onClick={() => setShowMembers((p) => !p)}>
              <Users size={12} color="var(--accent-green)" />
              <span style={styles.membersCount}>{users.length} online</span>
              <span style={{ fontSize: "10px", color: "var(--text-muted)" }}>
                {showMembers ? "▲" : "▼"}
              </span>
            </button>

            <AnimatePresence>
              {showMembers && (
                <motion.div
                  style={styles.membersList}
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: "auto", opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  transition={{ duration: 0.2 }}
                >
                  {users.map((u, i) => (
                    <div key={i} style={styles.memberItem}>
                      {u.avatar ? (
                        renderAvatar(u.avatar, u.username, 22)
                      ) : (
                        <div
                          style={{
                            ...styles.memberAvatar,
                            background: u.color || "var(--accent-cyan)",
                          }}
                        >
                          {u.username?.[0]?.toUpperCase()}
                        </div>
                      )}
                      <span style={styles.memberName}>
                        {u.username}
                        {u.username === currentUser && <span style={styles.youBadge}> you</span>}
                      </span>
                      <span style={styles.onlineDot} />
                    </div>
                  ))}
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Messages */}
          <div style={styles.messages}>
            {messages.length === 0 && (
              <div style={styles.emptyState}>
                <MessageSquare size={24} color="var(--text-muted)" />
                <p style={styles.emptyText}>No messages yet. Say hi to your team!</p>
              </div>
            )}
            {messages.map((msg, i) => {
              const senderObj = users.find((u) => u.username === msg.username);
              return (
                <RoomChatMessage
                  key={i}
                  msg={msg}
                  currentUser={currentUser}
                  senderAvatar={senderObj?.avatar}
                  senderColor={senderObj?.color}
                />
              );
            })}
            <div ref={chatBottomRef} />
          </div>

          {/* Last Edited By Indicator */}
          {lastEditedBy && (
            <div style={styles.lastEditedBar}>
              <span style={styles.lastEditedText}>
                Last edited by <strong style={{ color: "var(--accent-cyan)" }}>{lastEditedBy.username}</strong> at {new Date(lastEditedBy.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}
              </span>
            </div>
          )}

          {/* Input */}
          <div style={styles.inputRow}>
            <textarea
              ref={roomTextareaRef}
              style={styles.inputField}
              placeholder="Message the room…"
              value={roomInput}
              onChange={(e) => setRoomInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleRoomSend();
                }
              }}
              rows={1}
            />
            <button onClick={handleRoomSend} disabled={!roomInput.trim()} style={styles.sendBtn}>
              <Send size={14} />
            </button>
          </div>
        </div>
      )}

      {/* ── ASK AI TAB ───────────────────────────── */}
      {activeTab === "ai" && (
        <div style={styles.tabWrap}>
          {/* Messages */}
          <div style={styles.messages}>
            {chatHistory.length === 0 && (
              <div style={styles.emptyState}>
                <Brain size={28} color="var(--text-muted)" />
                <p style={styles.emptyText}>
                  Ask me anything about your code. I can see what's in the editor!
                </p>
                {/* Suggestion chips */}
                <div style={styles.chips}>
                  {["Explain this code", "How can I improve this?", "Find bugs", "Add comments"].map(
                    (chip) => (
                      <button
                        key={chip}
                        className="ai-suggestion-chip"
                        onClick={() => {
                          onSendChat(chip, code, language);
                        }}
                      >
                        {chip}
                      </button>
                    )
                  )}
                </div>
              </div>
            )}

            {chatHistory.map((msg, i) => (
              <AIChatMessage key={i} msg={msg} />
            ))}

            {chatLoading && (
              <motion.div style={styles.aiTyping} initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                <Brain size={11} color="var(--accent-cyan)" />
                <motion.span
                  style={{ fontSize: "12px", color: "var(--text-muted)" }}
                  animate={{ opacity: [1, 0.4, 1] }}
                  transition={{ duration: 1, repeat: Infinity }}
                >
                  AI is thinking…
                </motion.span>
              </motion.div>
            )}
            <div ref={aiBottomRef} />
          </div>

          {/* Input */}
          <div style={styles.inputRow}>
            <textarea
              ref={aiTextareaRef}
              style={styles.inputField}
              placeholder="Ask AI about your code…"
              value={aiInput}
              onChange={(e) => setAiInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleAiSend();
                }
              }}
              rows={1}
            />
            <button
              onClick={handleAiSend}
              disabled={chatLoading || !aiInput.trim()}
              style={styles.sendBtn}
            >
              {chatLoading ? (
                <Loader2 size={14} style={{ animation: "spin 0.7s linear infinite" }} />
              ) : (
                <Send size={14} />
              )}
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

// ── Styles ───────────────────────────────────────────────
const styles = {
  panel: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    background: "rgba(10, 10, 14, 0.75)",
    borderLeft: "1px solid var(--border)",
    overflow: "hidden",
  },
  tabs: {
    display: "flex",
    flexShrink: 0,
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-card)",
  },
  tab: {
    flex: 1,
    padding: "11px 4px",
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 600,
    fontFamily: "var(--font-body)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    transition: "color 0.15s",
  },
  tabWrap: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    overflow: "hidden",
  },

  membersHeader: { flexShrink: 0, borderBottom: "1px solid var(--border)" },
  membersToggle: {
    width: "100%",
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "8px 12px",
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  membersCount: {
    fontSize: "12px",
    color: "var(--accent-green)",
    fontFamily: "var(--font-mono)",
    flex: 1,
    textAlign: "left",
  },
  membersList: {
    overflow: "hidden",
    background: "var(--bg-card)",
    borderTop: "1px solid var(--border)",
  },
  memberItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 12px",
  },
  memberAvatar: {
    width: 22,
    height: 22,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "10px",
    fontWeight: 700,
    color: "#fff",
    flexShrink: 0,
  },
  memberName: { fontSize: "12px", color: "var(--text-secondary)", flex: 1 },
  youBadge: {
    fontSize: "10px",
    color: "var(--accent-cyan)",
    fontFamily: "var(--font-mono)",
  },
  onlineDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "var(--accent-green)",
    flexShrink: 0,
  },

  messages: {
    flex: 1,
    overflow: "auto",
    padding: "12px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
    padding: "32px 12px",
    textAlign: "center",
  },
  emptyText: {
    fontSize: "12px",
    color: "var(--text-muted)",
    lineHeight: 1.6,
    maxWidth: 200,
  },

  chips: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: "center",
    marginTop: 4,
  },

  msgWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    maxWidth: "90%",
  },
  bubble: { padding: "7px 10px" },
  msgText: {
    fontSize: "13px",
    lineHeight: 1.55,
    color: "var(--text-primary)",
  },
  aiLabel: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: "10px",
    fontWeight: 700,
    color: "var(--accent-cyan)",
    fontFamily: "var(--font-mono)",
    textTransform: "uppercase",
    paddingLeft: 4,
  },
  aiTyping: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 0",
  },

  inputRow: {
    display: "flex",
    gap: 8,
    padding: "10px 12px",
    borderTop: "1px solid var(--border)",
    background: "var(--bg-card)",
    flexShrink: 0,
    alignItems: "flex-end",
  },
  inputField: {
    flex: 1,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "8px 10px",
    color: "var(--text-primary)",
    fontSize: "13px",
    fontFamily: "var(--font-body)",
    outline: "none",
    resize: "none",
    height: "34px",
    maxHeight: "120px",
    overflowY: "auto",
    lineHeight: "1.4",
  },
  sendBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: "var(--accent-cyan)",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--bg-primary)",
    flexShrink: 0,
  },
  lastEditedBar: {
    padding: "6px 12px",
    background: "rgba(255, 255, 255, 0.02)",
    borderTop: "1px solid var(--border)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  lastEditedText: {
    fontSize: "11px",
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
  },
};

export default AIPanel;
